name: Deploy

on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          debug: true
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo rm -rf /var/www/vhosts/l2calculator.com/httpdocs &&
            sudo mkdir /var/www/vhosts/l2calculator.com/httpdocs &&
            sudo chown -R www-data:www-data /var/www/vhosts/l2calculator.com/httpdocs &&
            sudo chmod -R 775 /var/www/vhosts/l2calculator.com/httpdocs &&
            cd /var/www/vhosts/l2calculator.com/httpdocs &&
            sudo git clone git@github.com:Babilounet/l2-interlude-craft-calculator.git . &&
            sudo git fetch &&
            sudo git pull &&
            sudo chown -R www-data:www-data /var/www/vhosts/l2calculator.com/httpdocs &&
            sudo su - www-data &&
            composer update &&
            composer install