name: Deploy

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 1
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 8.2

      - name: Install Composer packages
        uses: "ramsey/composer-install@v2"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            *
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          debug: true
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/vhosts/l2calculator.com/httpdocs &&
            sudo rm -rf /var/www/vhosts/l2calculator.com/httpdocs/* &&
            git clone git@github.com:Babilounet/l2-interlude-craft-calculator.git . &&
            git fetch &&
            git pull &&
            composer update &&
            composer install &&
            sudo chown -R www-data:www-data /var/www/vhosts/l2calculator.com/httpdocs